backend:
  name: github
  branch: master
  repo: declanharrop/declanharrop.com

media_folder: static/img
public_folder: /img

collections:
  - name: 'team'
    label: 'Team'
    folder: 'src/team'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Team Member', name: 'title', widget: 'string' }
      - { label: 'bio', name: 'bio', widget: 'markdown' }

  - name: 'posts'
    label: 'Posts'
    folder: 'src/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Slug', name: 'title', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
